Move test utils in the src dir
PaulRBerg/prb-proxy pull request #176
Opened 2023-10-23 22:21 UTC by andreivladbrg

Same rational as [here](https://github.com/PaulRBerg/prb-math/pull/206)

### Changelog:

refactor: move test utils in src dir
build: install prb test as npm package
build: remove prb test git module
build: use correct path in update-precompiles script
ci: install node js dependencies in build and test job
chore: update remappings accordingly

2023-10-23 22:33 UTC, andreivladbrg commented
I see that the coverage has significantly decreased. This is because there are more contracts in `src` which don't have to be tested.

Is there a way to remove a path (~src/test/) from the coverage report?

2023-10-30 09:51 UTC, PaulRBerg requested changes
Thanks Andrei, just like in PRBMath, let's install Forge Std as a Node.js dependency.

> Is there a way to remove a path (~src/test/) from the coverage report?

Yes. See the `codecov.yml` file and the [Ignoring Paths](https://docs.codecov.com/docs/ignoring-paths) docs.

2023-10-30 09:51 UTC, PaulRBerg commented on package.json
> +  "dependencies": {
Has to be `devDependencies` and also has to be listed in `peerDependencies`

2023-10-30 11:39 UTC, andreivladbrg commented
Addressed everything in my latest commits.

I see that the slither job has failed and I am not sure why, is it because we need to add `pnpm install` step?

2023-10-30 13:48 UTC, PaulRBerg commented
Thanks!

> I see that the slither job has failed

Dunno, need to investigate but cannot at the moment

2023-11-16 16:32 UTC, andreivladbrg commented
Closing in favor of https://github.com/PaulRBerg/prb-proxy/pull/179

2023-11-16 16:32 UTC, closed without merging